### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by alemagio** [ehmicky/autoserver#4]
Hi, just discovered this repo, looks cool.
I would love to contribute, would you mind if I start adding a few unit tests? So I can take a bit of confidence with the project.

I saw your roadmap and testing doesn't look too far from the top right? :smile:

**Comment by ehmicky** [comment]
Hi @alemagio,

This repository is in standby mode at the moment. 
I unfortunately do not have time at the very moment to maintain it (except for quick dependencies upgrades) nor to review contributors PRs.
Thanks a lot for the offer for contribution though! :heart:  
I think forking the project would be the best approach though at that time.

**Comment by alemagio** [comment]
@ehmicky 
Oh ok, I perfectly understand.
No problem and thanks for the explanation too. :heart:
